---
#
# Push to registry
#
- name: Push the final image with the proper COMMIT HASH to Docker Registry
  docker_image:
    name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
    repository: "{{ docker_registry }}/{{ image_name }}:{{ code_commit_hash.stdout }}"
    push: true

- block:
  - name: Remove the local "latest" tag so we can tag as latest and push
    docker_image:
      name: "{{ docker_registry }}/{{ image_name }}:latest"
      state: absent

  - name: Push the final image with the tag "latest"
    docker_image:
      name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
      repository: "{{ docker_registry }}/{{ image_name }}:latest"
      push: true
  when: push_as_latest

