---
#
# Push to registry
#
- name: Push the final image with the proper COMMIT HASH to Docker Registry
  docker_image:
    name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
    repository: "{{ docker_registry }}/{{ image_name }}:{{ code_commit_hash.stdout }}"
    push: true
  when: custom_tag is undefined or not custom_tag

- block:
  - name: Remove the remote {{ custom_tag }} tag incase we already have it
    docker_image:
      name: "{{ docker_registry }}/{{ image_name }}:{{ custom_tag }}"
      state: absent

  - name: Push the final image with the tag {{ custom_tag }}
    docker_image:
      name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
      repository: "{{ docker_registry }}/{{ image_name }}:{{ custom_tag }}"
      push: true
  when: custom_tag is defined and custom_tag

- block:
  - name: Remove the remote {{ latest_tag_prefix }}latest tag so we can tag as {{ latest_tag_prefix }}latest and push
    docker_image:
      name: "{{ docker_registry }}/{{ image_name }}:{{ latest_tag_prefix }}latest"
      state: absent

  - name: Push the final image with the tag {{ latest_tag_prefix }}latest
    docker_image:
      name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
      repository: "{{ docker_registry }}/{{ image_name }}:{{ latest_tag_prefix }}latest"
      push: true
  when: push_as_latest

